"""
Token cost calculation and session-level cost tracking.

# PRODUCTION NOTE: In a real system, persist cost data to a database per
# user/org/request, set up budget alerts, expose a cost dashboard, and
# integrate with billing systems. Use OpenAI's usage API for reconciliation.
"""

# Standard library imports for data structures and type hints
import tiktoken                              # OpenAI's token counter library to accurately count tokens for billing
from dataclasses import dataclass, field     # Create lightweight data container classes with minimal boilerplate
from typing import Optional                  # Type hint for optional parameters and return values

# OpenAI pricing lookup table — prices in USD per 1,000 tokens
# Updated as of 2024; should be versioned and regularly updated as pricing changes
# Each model has separate input and output pricing (outputs typically cost more)
# This allows accurate cost calculation per LLM call without external API calls
# Note: Prices here are public list prices; volume discounts may apply via agreements
PRICING: dict[str, dict[str, float]] = {
    "gpt-4o-mini": {"input": 0.00015, "output": 0.00060},    # Cheapest option; suitable for simple tasks
    "gpt-4o": {"input": 0.005, "output": 0.015},              # Mid-range model; better quality, higher cost
    "gpt-4-turbo": {"input": 0.010, "output": 0.030},         # More expensive; better for complex reasoning
    "gpt-3.5-turbo": {"input": 0.0005, "output": 0.0015},     # Legacy model; lowest cost but lower quality
}


# Data container for cost information from a single LLM call
# Using @dataclass automatically generates __init__, __repr__, __eq__ methods
# This is used as the return type from calculate_cost() and input to session tracker
# Immutable design (no setters) encourages treating cost info as read-only records
@dataclass
class CostInfo:
    model: str                    # Which LLM was used (e.g., "gpt-4o-mini")
    input_tokens: int             # Number of tokens in the prompt sent to the LLM
    output_tokens: int            # Number of tokens generated by the LLM in its response
    input_cost_usd: float          # Cost in USD for input tokens (calculated and rounded to 6 decimals)
    output_cost_usd: float         # Cost in USD for output tokens (calculated and rounded to 6 decimals)
    total_cost_usd: float          # Sum of input and output costs for this single call


# Accumulates cost information across multiple LLM calls within a single session/process
# Provides visibility into total API spend per session for monitoring and optimization
# Design: Uses private attributes (_prefixed) with public methods to enforce encapsulation
# This prevents accidental modification of cumulative totals
class SessionCostTracker:
    """Accumulates cost across multiple LLM calls in a session."""

    # Constructor: Initialize all accumulators to zero at session start
    def __init__(self):
        self._total_input_tokens: int = 0           # Running total of all input tokens across calls
        self._total_output_tokens: int = 0          # Running total of all output tokens across calls
        self._total_cost_usd: float = 0.0            # Running total of USD spent across all calls
        self._call_count: int = 0                   # Counter of how many LLM calls were made

    # Record a single LLM call's cost into the session totals
    # Called after each LLM invocation to update cumulative costs
    # Design: Immutable CostInfo ensures no external code can modify recorded data
    def record(self, cost_info: CostInfo) -> None:
        # Add this call's tokens and cost to running totals
        self._total_input_tokens += cost_info.input_tokens # self._total_input_tokens = self._total_input_tokens + cost_info.input_tokens
        self._total_output_tokens += cost_info.output_tokens
        self._total_cost_usd += cost_info.total_cost_usd
        # Increment call counter to track how many API calls were made
        self._call_count += 1

    # Property decorator exposes read-only summary without allowing external modification
    # Returns a plain dictionary for easy serialization (JSON, logging, etc.)
    # Rounding ensures cost values are human-readable (6 decimal places)
    @property
    def summary(self) -> dict:
        return {
            "calls": self._call_count,                          # Number of API calls made
            "total_input_tokens": self._total_input_tokens,     # Sum of all prompt tokens
            "total_output_tokens": self._total_output_tokens,   # Sum of all response tokens
            "total_cost_usd": round(self._total_cost_usd, 6),   # Total spend for the session
        }


# Global session tracker instance — exists for the lifetime of the process
# Initialized once when this module is imported
# All LLM calls in the session automatically record to this tracker
# Note: In production, this should be replaced with a database backend for:
#   - Persistence across process restarts
#   - Per-user/org/request cost attribution
#   - Budget alerts and cost dashboards
#   - Billing system integration
session_tracker = SessionCostTracker()


# Count the exact number of tokens in text for a given LLM model
# Tokens are how OpenAI bills; knowing token count is critical for cost estimation
# Parameters:
#   text: The string to count tokens in (prompt or response)
#   model: Which LLM's tokenizer to use (different models may tokenize differently)
# Returns: Integer count of tokens
# Why this function: Accurate token counting is essential for cost calculation and avoiding token limit surprises
def count_tokens(text: str, model: str = "gpt-4o-mini") -> int:
    """Count tokens in a string using tiktoken."""
    try:
        # Try to get the exact tokenizer for the specified model
        # This ensures accuracy for models with custom tokenization (e.g., gpt-4o vs gpt-3.5-turbo)
        encoding = tiktoken.encoding_for_model(model)
    except KeyError:
        # If model not recognized, fall back to the standard encoding used by most modern models
        # cl100k_base is OpenAI's universal tokenizer for most current models
        # This prevents failures for models not yet in tiktoken's database
        encoding = tiktoken.get_encoding("cl100k_base")
    # Encode the text to tokens and return the length
    return len(encoding.encode(text))


# Calculate the cost in USD for a single LLM call and optionally record it to session tracker
# This is the main function called after each LLM invocation to track API spend
# Parameters:
#   model: Which LLM model was used (affects pricing lookup)
#   input_tokens: Number of tokens in the prompt sent to the LLM
#   output_tokens: Number of tokens in the LLM's response
#   record_to_session: Whether to add this cost to the running session total (default True)
# Returns: CostInfo object containing breakdown of costs for this call
# Why this function: Centralizes cost calculation logic to prevent duplication and ensure consistency
def calculate_cost(
    model: str,
    input_tokens: int,
    output_tokens: int,
    record_to_session: bool = True,
) -> CostInfo:
    """Calculate cost for an LLM call and optionally record to session tracker."""
    # Look up pricing for the model; fall back to gpt-4o-mini if not found
    # This prevents crashes for unknown models but uses a reasonable default
    pricing = PRICING.get(model, PRICING["gpt-4o-mini"])
    
    # Calculate input cost: (tokens / 1000) * (price per 1000 tokens)
    # Division by 1000 converts from "price per 1k tokens" to "price per token"
    # Multiply by actual token count to get the total cost
    input_cost = (input_tokens / 1000) * pricing["input"]
    
    # Calculate output cost: same formula as input but using output pricing
    # Output tokens typically cost more than input (model has to work harder to generate)
    output_cost = (output_tokens / 1000) * pricing["output"]
    
    # Sum input and output costs to get total cost for this call
    total = input_cost + output_cost

    # Create CostInfo object with all calculated values
    # Rounding to 6 decimals ensures USD currency format (cents are 2 decimals, but we go finer for accuracy)
    info = CostInfo(
        model=model,                                      # Record which model was used
        input_tokens=input_tokens,                        # Store actual token counts for logging
        output_tokens=output_tokens,
        input_cost_usd=round(input_cost, 6),              # Round to avoid floating-point precision issues
        output_cost_usd=round(output_cost, 6),
        total_cost_usd=round(total, 6),
    )

    # Optionally record this cost to the session tracker for cumulative monitoring
    # record_to_session=False is used when you want cost calculation without automatic tracking
    # (e.g., for testing or partial/alternate flows)
    if record_to_session:
        session_tracker.record(info)

    # Return the cost breakdown so caller can log, display, or use it
    return info


# ============================================================================
# Demo / Test Section: Only runs when this file is executed directly
# ============================================================================
if __name__ == "__main__":
    # Sample prompt that would be sent to the LLM (represents user input)
    prompt = "Classify this ticket: My order hasn't arrived after 2 weeks!"
    # Sample response from the LLM (represents model output)
    # In real usage, this would be actual JSON classification output
    response = '{"issue_category": "delivery_issue", "priority": "high"}'

    # Count tokens in the prompt using the default gpt-4o-mini tokenizer
    # This simulates what would happen before sending to OpenAI
    in_tokens = count_tokens(prompt)
    
    # Count tokens in the response using the same tokenizer
    # In production, this would come from OpenAI's usage metadata
    out_tokens = count_tokens(response)
    
    # Calculate the cost for this single LLM call
    # record_to_session defaults to True, so this updates the session tracker
    cost = calculate_cost("gpt-4o-mini", in_tokens, out_tokens)

    # Display the breakdown of tokens and costs for this single call
    print(f"Input tokens : {cost.input_tokens}")
    print(f"Output tokens: {cost.output_tokens}")
    print(f"Input cost   : ${cost.input_cost_usd:.6f}")
    print(f"Output cost  : ${cost.output_cost_usd:.6f}")
    print(f"Total cost   : ${cost.total_cost_usd:.6f}")
    
    # Display the cumulative session totals after this call
    # Demonstrates how session tracker accumulates costs across calls
    print(f"Session total: {session_tracker.summary}")
